# Generated by Django 4.2.6 on 2023-12-09 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Official_Email', models.EmailField(max_length=254, unique=True)),
                ('Official_website', models.CharField(max_length=1000)),
                ('Registiration_no', models.CharField(max_length=1000)),
                ('Location', models.CharField(max_length=1000)),
                ('Franchise', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Phone', models.BigIntegerField(unique=True)),
                ('Gender', models.CharField(max_length=10)),
                ('Country', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=30)),
                ('City', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=100)),
                ('Role', models.CharField(max_length=200)),
                ('Employee_Id_no', models.BigIntegerField()),
                ('Social1', models.CharField(blank=True, max_length=50)),
                ('Social2', models.CharField(blank=True, max_length=50)),
                ('Social3', models.CharField(blank=True, max_length=50)),
                ('Company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.company')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Phone', models.BigIntegerField(unique=True)),
                ('Gender', models.CharField(max_length=10)),
                ('Country', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=30)),
                ('City', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=100)),
                ('Passed', models.BooleanField(blank=True, null=True)),
                ('University_name', models.CharField(max_length=500)),
                ('Course', models.CharField(max_length=200)),
                ('Roll_no', models.BigIntegerField()),
                ('Resume', models.FileField(upload_to='Documents/Student/')),
                ('Social1', models.CharField(blank=True, max_length=50)),
                ('Social2', models.CharField(blank=True, max_length=50)),
                ('Social3', models.CharField(blank=True, max_length=50)),
                ('Skills', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Project', models.FileField(upload_to='Documents/Projects/')),
                ('Perks', models.CharField(max_length=100)),
                ('Skill_req', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=1000)),
                ('Employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.employe')),
            ],
        ),
    ]
