# Generated by Django 4.2.6 on 2023-12-09 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_project_duration_project_student_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Passed',
            field=models.CharField(max_length=10),
        ),
    ]
