# Generated by Django 4.2.6 on 2023-12-12 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_student_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='Stipend',
            field=models.IntegerField(default=111111),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
