# Generated by Django 4.2.6 on 2023-12-12 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_project_company_project_stipend_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Duration',
            field=models.DateField(null=True),
        ),
    ]
