# Generated by Django 4.2.6 on 2023-12-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_project_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='status',
            new_name='Status',
        ),
        migrations.AddField(
            model_name='project',
            name='Final_Submit',
            field=models.FileField(null=True, upload_to='Documents/Final_submission/'),
        ),
    ]
