# Generated by Django 4.2.6 on 2023-12-23 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_status_project_status_project_final_submit'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Last_update',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 12, 23, 13, 1, 6, 749661), null=True),
        ),
    ]
