# Generated by Django 4.2.6 on 2023-12-24 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_project_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='Final_Submit',
        ),
        migrations.AlterField(
            model_name='project',
            name='Last_update',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 12, 24, 15, 23, 34, 29325), null=True),
        ),
    ]
