# Generated by Django 4.2.6 on 2023-12-26 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_project_final_submit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='College_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='Documents/Student/Profile_Image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='Last_update',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 12, 27, 0, 41, 45, 7156), null=True),
        ),
    ]
