# Generated by Django 4.2.6 on 2024-01-05 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_student_college_name_student_is_suspended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Last_update',
            field=models.DateField(default=datetime.datetime(2024, 1, 5, 23, 35, 41, 749935)),
        ),
    ]
