# Generated by Django 4.2.6 on 2024-01-05 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_project_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Suspend_till',
            field=models.DateField(default=datetime.date(2024, 1, 5)),
        ),
        migrations.AlterField(
            model_name='project',
            name='Last_update',
            field=models.DateField(default=datetime.datetime(2024, 1, 5, 23, 43, 45, 812915)),
        ),
    ]
