# Generated by Django 4.2.6 on 2024-01-05 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_student_suspend_till_alter_project_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Last_update',
            field=models.DateField(default=datetime.datetime(2024, 1, 5, 23, 44, 5, 691680)),
        ),
    ]
