# Generated by Django 4.2.6 on 2024-02-10 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_project_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Exp1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='Exp2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='Exp3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='Project',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='Last_update',
            field=models.DateField(default=datetime.datetime(2024, 2, 10, 23, 2, 26, 402132)),
        ),
        migrations.AlterField(
            model_name='student',
            name='Social1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='Social2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='Social3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='Suspend_till',
            field=models.DateField(default=datetime.date(2024, 2, 10)),
        ),
    ]
