# Generated by Django 4.2.6 on 2024-02-10 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_student_exp1_student_exp2_student_exp3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Project',
            new_name='Projects',
        ),
        migrations.AlterField(
            model_name='project',
            name='Last_update',
            field=models.DateField(default=datetime.datetime(2024, 2, 10, 23, 12, 1, 57596)),
        ),
    ]
