# Generated by Django 4.2.6 on 2024-02-19 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_student_suspend_till'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Last_update',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Suspend_till',
            field=models.DateField(default=datetime.datetime(2024, 2, 19, 18, 46, 1, 241158, tzinfo=datetime.timezone.utc)),
        ),
    ]
