# Generated by Django 4.2.6 on 2024-03-11 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_project_last_update_alter_student_suspend_till_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='Duration',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Last_update',
            field=models.DateField(default=datetime.datetime(2024, 3, 11, 14, 10, 16, 860661, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='Suspend_till',
            field=models.DateField(default=datetime.datetime(2024, 3, 11, 14, 10, 16, 858665, tzinfo=datetime.timezone.utc)),
        ),
    ]
