# Generated by Django 4.2.6 on 2024-03-11 17:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_project_progress_alter_project_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Last_update',
            field=models.DateField(default=datetime.datetime(2024, 3, 11, 17, 15, 20, 702704, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='Suspend_till',
            field=models.DateField(default=datetime.datetime(2024, 3, 11, 17, 15, 20, 700705, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.CharField(max_length=3000)),
                ('Employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.employe')),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.project')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.student')),
            ],
        ),
    ]
