# Generated by Django 4.2.6 on 2024-03-11 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_project_last_update_alter_student_suspend_till_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chats',
            new_name='Chat',
        ),
        migrations.AlterField(
            model_name='project',
            name='Last_update',
            field=models.DateField(default=datetime.datetime(2024, 3, 11, 17, 26, 50, 290022, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='Suspend_till',
            field=models.DateField(default=datetime.datetime(2024, 3, 11, 17, 26, 50, 288023, tzinfo=datetime.timezone.utc)),
        ),
    ]
