# Generated by Django 4.2.6 on 2024-03-13 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_rename_chats_chat_alter_project_last_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 13, 18, 6, 25, 578488, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='chat',
            name='Task_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='Last_update',
            field=models.DateField(default=datetime.datetime(2024, 3, 13, 18, 6, 25, 555501, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='Suspend_till',
            field=models.DateField(default=datetime.datetime(2024, 3, 13, 18, 6, 25, 553502, tzinfo=datetime.timezone.utc)),
        ),
    ]
